trigger:
  branches:
    include:
      - main

pool:
  name: 'OnPremPool'  # Replace with the name of your on-premises agent pool

variables:
  tosciPath: 'C:\\Program Files (x86)\\TRICENTIS\\Tosca Testsuite\\ToscaCI'  # Path to ToscaCI.exe
  workspacePath: 'H:\\toscaprojects\\saucelabdemo\\saucelabdemo.tws'  # Path to the Tosca workspace
  executionList: 'LoginTestExecution'  # Name of the execution list in Tosca
  resultFilePath: 'H:\\toscaprojects\\saucelabdemo\\Results.xml'  # Path to save test results

stages:
  - stage: 'RunToscaTests'
    displayName: 'Run Tosca Tests'
    jobs:
      - job: 'RunTests'
        displayName: 'Run Tosca Tests on On-Premises Agent'
        steps:
          # Verify ToscaCI Installation
          - powershell: |
              if (-Not (Test-Path "$(tosciPath)\\ToscaCI.exe")) {
                  Write-Error "ToscaCI.exe not found. Ensure Tosca is installed and the path is correct."
                  exit 1
              }
            displayName: 'Verify ToscaCI Installation'

          # Execute Tosca Tests
          - powershell: |
              "$(tosciPath)\\ToscaCI.exe" execute-testsuite `
              --workspace "$(workspacePath)" `
              --executionlist "$(executionList)" `
              --resultfile "$(resultFilePath)"
            displayName: 'Execute Tosca Tests'

          # Publish Test Results
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '$(resultFilePath)'
              failTaskOnFailedTests: true
