trigger:
  branches:
    include:
      - main

# Using Microsoft-hosted agents implicitly
stages:
  - stage: 'RunToscaTests'
    displayName: 'Run Tosca Tests'
    jobs:
      - job: 'RunTests'
        displayName: 'Execute Tosca Tests'
        steps:
          # Verify ToscaCI Installation
          - powershell: |
              if (-Not (Test-Path "C:\\Program Files (x86)\\TRICENTIS\\Tosca Testsuite\\ToscaCI\\ToscaCI.exe")) {
                  Write-Error "ToscaCI.exe not found. Ensure Tosca is installed."
                  exit 1
              }
            displayName: 'Verify ToscaCI Installation'

          # Execute Tosca Tests
          - powershell: |
              "C:\\Program Files (x86)\\TRICENTIS\\Tosca Testsuite\\ToscaCI\\ToscaCI.exe" execute-testsuite `
              --workspace "H:\\toscaprojects\\saucelabdemo\\saucelabdemo.tws" `
              --executionlist "LoginTestExecution" `
              --resultfile "H:\\toscaprojects\\saucelabdemo\\Results.xml"
            displayName: 'Run Tosca Tests'

          # Publish Test Results
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'C:\\Path\\To\\Results.xml'
              failTaskOnFailedTests: true
